//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastComments.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FastComments.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string acw_add {
            get {
                return ResourceManager.GetString("acw_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string acw_browse {
            get {
                return ResourceManager.GetString("acw_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string acw_done {
            get {
                return ResourceManager.GetString("acw_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Code.
        /// </summary>
        public static string acw_newcode {
            get {
                return ResourceManager.GetString("acw_newcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Comment Text.
        /// </summary>
        public static string acw_newcommenttext {
            get {
                return ResourceManager.GetString("acw_newcommenttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} comments).
        /// </summary>
        public static string acw_title {
            get {
                return ResourceManager.GetString("acw_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comments.
        /// </summary>
        public static string acw_titleorig {
            get {
                return ResourceManager.GetString("acw_titleorig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ecw_cancel {
            get {
                return ResourceManager.GetString("ecw_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string ecw_key {
            get {
                return ResourceManager.GetString("ecw_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ecw_ok {
            get {
                return ResourceManager.GetString("ecw_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string ecw_text {
            get {
                return ResourceManager.GetString("ecw_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Comment.
        /// </summary>
        public static string ecw_title {
            get {
                return ResourceManager.GetString("ecw_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string hw_code {
            get {
                return ResourceManager.GetString("hw_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string hw_text {
            get {
                return ResourceManager.GetString("hw_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string hw_title {
            get {
                return ResourceManager.GetString("hw_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code already used. Use different code..
        /// </summary>
        public static string mb_codeused {
            get {
                return ResourceManager.GetString("mb_codeused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Copy.
        /// </summary>
        public static string mw_autocopy {
            get {
                return ResourceManager.GetString("mw_autocopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy comment box to Clipboard.
        /// </summary>
        public static string mw_autocopy_tt {
            get {
                return ResourceManager.GetString("mw_autocopy_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string mw_code {
            get {
                return ResourceManager.GetString("mw_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string mw_enter {
            get {
                return ResourceManager.GetString("mw_enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help....
        /// </summary>
        public static string mw_help {
            get {
                return ResourceManager.GetString("mw_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show available codes.
        /// </summary>
        public static string mw_help_tt {
            get {
                return ResourceManager.GetString("mw_help_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string mw_settings {
            get {
                return ResourceManager.GetString("mw_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update code/comment database.
        /// </summary>
        public static string mw_settings_tt {
            get {
                return ResourceManager.GetString("mw_settings_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string mw_undo {
            get {
                return ResourceManager.GetString("mw_undo", resourceCulture);
            }
        }
    }
}
